// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameMessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameMessages {

  /// <summary>Holder for reflection information generated from GameMessages.proto</summary>
  public static partial class GameMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for GameMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJHYW1lTWVzc2FnZXMucHJvdG8SDEdhbWVNZXNzYWdlcyJVCg5TZXNzaW9u",
            "TWVzc2FnZRIOCgZzZW5kZXIYASABKAQSMwoEdHlwZRgCIAEoDjIlLkdhbWVN",
            "ZXNzYWdlcy5TZXNzaW9uUHJvdG9NZXNzYWdlVHlwZSLmAQoTU3Bhd25HYW1l",
            "T2JqZWN0RGF0YRIPCgdyZXF1ZXN0GAEgASgIEg4KBnNlbmRlchgCIAEoBBIR",
            "CglhdXRob3JpdHkYAyABKAQSDwoHb2JqTmFtZRgEIAEoCRIOCgZzcGF3blgY",
            "BSABKAISDgoGc3Bhd25ZGAYgASgCEg4KBnNwYXduWhgHIAEoAhITCgZ3aXRo",
            "SUQYCCABKARIAIgBARIhChRyZXF1ZXN0b3JBdXRvUG9zc2VzcxgJIAEoBEgB",
            "iAEBQgkKB193aXRoSURCFwoVX3JlcXVlc3RvckF1dG9Qb3NzZXNzIuYDChRT",
            "aW1wbGVHYW1lT2JqZWN0U3luYxIPCgdyZXF1ZXN0GAEgASgIEg4KBnNlbmRl",
            "chgCIAEoBBIRCglhdXRob3JpdHkYAyABKAQSDgoGdGFyZ2V0GAQgASgEEgwK",
            "BHBvc1gYBSABKAISDAoEcG9zWRgGIAEoAhIMCgRwb3NaGAcgASgCEgwKBHJv",
            "dFgYCCABKAISDAoEcm90WRgJIAEoAhIMCgRyb3RaGAogASgCEgwKBHZlbFgY",
            "CyABKAISDAoEdmVsWRgMIAEoAhIMCgR2ZWxaGA0gASgCEg8KB3RvcnF1ZVgY",
            "DiABKAISDwoHdG9ycXVlWRgPIAEoAhIPCgd0b3JxdWVaGBAgASgCEjwKBWZE",
            "YXRhGBEgAygLMi0uR2FtZU1lc3NhZ2VzLlNpbXBsZUdhbWVPYmplY3RTeW5j",
            "LkZEYXRhRW50cnkSPgoGdWxEYXRhGBIgAygLMi4uR2FtZU1lc3NhZ2VzLlNp",
            "bXBsZUdhbWVPYmplY3RTeW5jLlVsRGF0YUVudHJ5GiwKCkZEYXRhRW50cnkS",
            "CwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgCOgI4ARotCgtVbERhdGFFbnRy",
            "eRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAQ6AjgBIqgDChdQbGF5ZXJD",
            "b250cm9sbGVyTWVzc2FnZRIPCgdyZXF1ZXN0GAEgASgIEg4KBnNlbmRlchgC",
            "IAEoBBIRCglhdXRob3JpdHkYAyABKAQSNwoEdHlwZRgEIAEoDjIpLkdhbWVN",
            "ZXNzYWdlcy5QbGF5ZXJDb250cm9sbGVyTWVzc2FnZVR5cGUSDgoGdGFyZ2V0",
            "GAUgASgEEg0KBW90aGVyGAYgASgEEkEKBmlucHV0cxgHIAMoCzIxLkdhbWVN",
            "ZXNzYWdlcy5QbGF5ZXJDb250cm9sbGVyTWVzc2FnZS5JbnB1dHNFbnRyeRIX",
            "Cg9Nb3ZlbWVudFZlY3RvclgYCCABKAISFwoPTW92ZW1lbnRWZWN0b3JZGAkg",
            "ASgCEiAKGFJvdGF0ZVZlY3RvckFjY3VtdWxhdG9yWBgKIAEoAhIgChhSb3Rh",
            "dGVWZWN0b3JBY2N1bXVsYXRvclkYCyABKAIaSAoLSW5wdXRzRW50cnkSCwoD",
            "a2V5GAEgASgJEigKBXZhbHVlGAIgASgLMhkuR2FtZU1lc3NhZ2VzLkFjdGlv",
            "bklucHV0OgI4ASJqCgtBY3Rpb25JbnB1dBISCgphY3Rpb25OYW1lGAEgASgJ",
            "Eg8KB3ByZXNzZWQYAiABKAgSEAoIcmVsZWFzZWQYAyABKAgSEwoLanVzdFBy",
            "ZXNzZWQYBCABKAgSDwoHY2hhbmdlZBgFIAEoCCqFAwoXU2Vzc2lvblByb3Rv",
            "TWVzc2FnZVR5cGUSEQoNU0VTU0lPTl9FUlJPUhAAEhIKDlJFUVVFU1RfQ09O",
            "RklHEAESFwoTUkVRVUVTVF9QUk9HUkVTU0lPThACEhkKFVJFUVVFU1RfUExB",
            "WUVST1BUSU9OUxADEhcKE1JFUVVFU1RfUExBWUVSU1RBVEUQBBIaChZSRVFV",
            "RVNUX1NFU1NJT05PUFRJT05TEAUSHwobUkVRVUVTVF9BU1NJR05QTEFZRVJP",
            "UFRJT05TEAYSEwoPUkVTUE9OU0VfQ09ORklHEAsSGAoUUkVTUE9OU0VfUFJP",
            "R1JFU1NJT04QDBIaChZSRVNQT05TRV9QTEFZRVJPUFRJT05TEA0SGAoUUkVT",
            "UE9OU0VfUExBWUVSU1RBVEUQDhIbChdSRVNQT05TRV9TRVNTSU9OT1BUSU9O",
            "UxAPEiAKHFJFU1BPTlNFX0FTU0lHTlBMQVlFUk9QVElPTlMQEBIVChFDT01N",
            "QU5EX1NUQVJUR0FNRRAVKlcKG1BsYXllckNvbnRyb2xsZXJNZXNzYWdlVHlw",
            "ZRIMCghQQ19FUlJPUhAAEgsKB1BPU1NFU1MQARINCglJTlBVVF9PTkUQCxIO",
            "CgpJTlBVVF9GVUxMEAxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameMessages.SessionProtoMessageType), typeof(global::GameMessages.PlayerControllerMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessages.SessionMessage), global::GameMessages.SessionMessage.Parser, new[]{ "Sender", "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessages.SpawnGameObjectData), global::GameMessages.SpawnGameObjectData.Parser, new[]{ "Request", "Sender", "Authority", "ObjName", "SpawnX", "SpawnY", "SpawnZ", "WithID", "RequestorAutoPossess" }, new[]{ "WithID", "RequestorAutoPossess" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessages.SimpleGameObjectSync), global::GameMessages.SimpleGameObjectSync.Parser, new[]{ "Request", "Sender", "Authority", "Target", "PosX", "PosY", "PosZ", "RotX", "RotY", "RotZ", "VelX", "VelY", "VelZ", "TorqueX", "TorqueY", "TorqueZ", "FData", "UlData" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessages.PlayerControllerMessage), global::GameMessages.PlayerControllerMessage.Parser, new[]{ "Request", "Sender", "Authority", "Type", "Target", "Other", "Inputs", "MovementVectorX", "MovementVectorY", "RotateVectorAccumulatorX", "RotateVectorAccumulatorY" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameMessages.ActionInput), global::GameMessages.ActionInput.Parser, new[]{ "ActionName", "Pressed", "Released", "JustPressed", "Changed" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum SessionProtoMessageType {
    [pbr::OriginalName("SESSION_ERROR")] SessionError = 0,
    [pbr::OriginalName("REQUEST_CONFIG")] RequestConfig = 1,
    [pbr::OriginalName("REQUEST_PROGRESSION")] RequestProgression = 2,
    [pbr::OriginalName("REQUEST_PLAYEROPTIONS")] RequestPlayeroptions = 3,
    [pbr::OriginalName("REQUEST_PLAYERSTATE")] RequestPlayerstate = 4,
    [pbr::OriginalName("REQUEST_SESSIONOPTIONS")] RequestSessionoptions = 5,
    [pbr::OriginalName("REQUEST_ASSIGNPLAYEROPTIONS")] RequestAssignplayeroptions = 6,
    [pbr::OriginalName("RESPONSE_CONFIG")] ResponseConfig = 11,
    [pbr::OriginalName("RESPONSE_PROGRESSION")] ResponseProgression = 12,
    [pbr::OriginalName("RESPONSE_PLAYEROPTIONS")] ResponsePlayeroptions = 13,
    [pbr::OriginalName("RESPONSE_PLAYERSTATE")] ResponsePlayerstate = 14,
    [pbr::OriginalName("RESPONSE_SESSIONOPTIONS")] ResponseSessionoptions = 15,
    [pbr::OriginalName("RESPONSE_ASSIGNPLAYEROPTIONS")] ResponseAssignplayeroptions = 16,
    [pbr::OriginalName("COMMAND_STARTGAME")] CommandStartgame = 21,
  }

  public enum PlayerControllerMessageType {
    [pbr::OriginalName("PC_ERROR")] PcError = 0,
    [pbr::OriginalName("POSSESS")] Possess = 1,
    [pbr::OriginalName("INPUT_ONE")] InputOne = 11,
    [pbr::OriginalName("INPUT_FULL")] InputFull = 12,
  }

  #endregion

  #region Messages
  [global::System.SerializableAttribute]
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SessionMessage : pb::IMessage<SessionMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionMessage> _parser = new pb::MessageParser<SessionMessage>(() => new SessionMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessages.GameMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionMessage(SessionMessage other) : this() {
      sender_ = other.sender_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionMessage Clone() {
      return new SessionMessage(this);
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 1;
    private ulong sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::GameMessages.SessionProtoMessageType type_ = global::GameMessages.SessionProtoMessageType.SessionError;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameMessages.SessionProtoMessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sender != other.Sender) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Sender != 0UL) hash ^= Sender.GetHashCode();
      if (Type != global::GameMessages.SessionProtoMessageType.SessionError) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sender != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Sender);
      }
      if (Type != global::GameMessages.SessionProtoMessageType.SessionError) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sender != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Sender);
      }
      if (Type != global::GameMessages.SessionProtoMessageType.SessionError) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Sender != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Sender);
      }
      if (Type != global::GameMessages.SessionProtoMessageType.SessionError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionMessage other) {
      if (other == null) {
        return;
      }
      if (other.Sender != 0UL) {
        Sender = other.Sender;
      }
      if (other.Type != global::GameMessages.SessionProtoMessageType.SessionError) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sender = input.ReadUInt64();
            break;
          }
          case 16: {
            Type = (global::GameMessages.SessionProtoMessageType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Sender = input.ReadUInt64();
            break;
          }
          case 16: {
            Type = (global::GameMessages.SessionProtoMessageType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.SerializableAttribute]
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpawnGameObjectData : pb::IMessage<SpawnGameObjectData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpawnGameObjectData> _parser = new pb::MessageParser<SpawnGameObjectData>(() => new SpawnGameObjectData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpawnGameObjectData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessages.GameMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpawnGameObjectData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpawnGameObjectData(SpawnGameObjectData other) : this() {
      _hasBits0 = other._hasBits0;
      request_ = other.request_;
      sender_ = other.sender_;
      authority_ = other.authority_;
      objName_ = other.objName_;
      spawnX_ = other.spawnX_;
      spawnY_ = other.spawnY_;
      spawnZ_ = other.spawnZ_;
      withID_ = other.withID_;
      requestorAutoPossess_ = other.requestorAutoPossess_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpawnGameObjectData Clone() {
      return new SpawnGameObjectData(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private bool request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 2;
    private ulong sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "authority" field.</summary>
    public const int AuthorityFieldNumber = 3;
    private ulong authority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Authority {
      get { return authority_; }
      set {
        authority_ = value;
      }
    }

    /// <summary>Field number for the "objName" field.</summary>
    public const int ObjNameFieldNumber = 4;
    private string objName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObjName {
      get { return objName_; }
      set {
        objName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "spawnX" field.</summary>
    public const int SpawnXFieldNumber = 5;
    private float spawnX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float SpawnX {
      get { return spawnX_; }
      set {
        spawnX_ = value;
      }
    }

    /// <summary>Field number for the "spawnY" field.</summary>
    public const int SpawnYFieldNumber = 6;
    private float spawnY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float SpawnY {
      get { return spawnY_; }
      set {
        spawnY_ = value;
      }
    }

    /// <summary>Field number for the "spawnZ" field.</summary>
    public const int SpawnZFieldNumber = 7;
    private float spawnZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float SpawnZ {
      get { return spawnZ_; }
      set {
        spawnZ_ = value;
      }
    }

    /// <summary>Field number for the "withID" field.</summary>
    public const int WithIDFieldNumber = 8;
    private readonly static ulong WithIDDefaultValue = 0UL;

    private ulong withID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong WithID {
      get { if ((_hasBits0 & 1) != 0) { return withID_; } else { return WithIDDefaultValue; } }
      set {
        _hasBits0 |= 1;
        withID_ = value;
      }
    }
    /// <summary>Gets whether the "withID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWithID {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "withID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWithID() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "requestorAutoPossess" field.</summary>
    public const int RequestorAutoPossessFieldNumber = 9;
    private readonly static ulong RequestorAutoPossessDefaultValue = 0UL;

    private ulong requestorAutoPossess_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RequestorAutoPossess {
      get { if ((_hasBits0 & 2) != 0) { return requestorAutoPossess_; } else { return RequestorAutoPossessDefaultValue; } }
      set {
        _hasBits0 |= 2;
        requestorAutoPossess_ = value;
      }
    }
    /// <summary>Gets whether the "requestorAutoPossess" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRequestorAutoPossess {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "requestorAutoPossess" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequestorAutoPossess() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpawnGameObjectData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpawnGameObjectData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Request != other.Request) return false;
      if (Sender != other.Sender) return false;
      if (Authority != other.Authority) return false;
      if (ObjName != other.ObjName) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SpawnX, other.SpawnX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SpawnY, other.SpawnY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SpawnZ, other.SpawnZ)) return false;
      if (WithID != other.WithID) return false;
      if (RequestorAutoPossess != other.RequestorAutoPossess) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Request != false) hash ^= Request.GetHashCode();
      if (Sender != 0UL) hash ^= Sender.GetHashCode();
      if (Authority != 0UL) hash ^= Authority.GetHashCode();
      if (ObjName.Length != 0) hash ^= ObjName.GetHashCode();
      if (SpawnX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SpawnX);
      if (SpawnY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SpawnY);
      if (SpawnZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SpawnZ);
      if (HasWithID) hash ^= WithID.GetHashCode();
      if (HasRequestorAutoPossess) hash ^= RequestorAutoPossess.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Request != false) {
        output.WriteRawTag(8);
        output.WriteBool(Request);
      }
      if (Sender != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Sender);
      }
      if (Authority != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Authority);
      }
      if (ObjName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ObjName);
      }
      if (SpawnX != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(SpawnX);
      }
      if (SpawnY != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(SpawnY);
      }
      if (SpawnZ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(SpawnZ);
      }
      if (HasWithID) {
        output.WriteRawTag(64);
        output.WriteUInt64(WithID);
      }
      if (HasRequestorAutoPossess) {
        output.WriteRawTag(72);
        output.WriteUInt64(RequestorAutoPossess);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Request != false) {
        output.WriteRawTag(8);
        output.WriteBool(Request);
      }
      if (Sender != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Sender);
      }
      if (Authority != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Authority);
      }
      if (ObjName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ObjName);
      }
      if (SpawnX != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(SpawnX);
      }
      if (SpawnY != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(SpawnY);
      }
      if (SpawnZ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(SpawnZ);
      }
      if (HasWithID) {
        output.WriteRawTag(64);
        output.WriteUInt64(WithID);
      }
      if (HasRequestorAutoPossess) {
        output.WriteRawTag(72);
        output.WriteUInt64(RequestorAutoPossess);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Request != false) {
        size += 1 + 1;
      }
      if (Sender != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Sender);
      }
      if (Authority != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Authority);
      }
      if (ObjName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObjName);
      }
      if (SpawnX != 0F) {
        size += 1 + 4;
      }
      if (SpawnY != 0F) {
        size += 1 + 4;
      }
      if (SpawnZ != 0F) {
        size += 1 + 4;
      }
      if (HasWithID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(WithID);
      }
      if (HasRequestorAutoPossess) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RequestorAutoPossess);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpawnGameObjectData other) {
      if (other == null) {
        return;
      }
      if (other.Request != false) {
        Request = other.Request;
      }
      if (other.Sender != 0UL) {
        Sender = other.Sender;
      }
      if (other.Authority != 0UL) {
        Authority = other.Authority;
      }
      if (other.ObjName.Length != 0) {
        ObjName = other.ObjName;
      }
      if (other.SpawnX != 0F) {
        SpawnX = other.SpawnX;
      }
      if (other.SpawnY != 0F) {
        SpawnY = other.SpawnY;
      }
      if (other.SpawnZ != 0F) {
        SpawnZ = other.SpawnZ;
      }
      if (other.HasWithID) {
        WithID = other.WithID;
      }
      if (other.HasRequestorAutoPossess) {
        RequestorAutoPossess = other.RequestorAutoPossess;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Request = input.ReadBool();
            break;
          }
          case 16: {
            Sender = input.ReadUInt64();
            break;
          }
          case 24: {
            Authority = input.ReadUInt64();
            break;
          }
          case 34: {
            ObjName = input.ReadString();
            break;
          }
          case 45: {
            SpawnX = input.ReadFloat();
            break;
          }
          case 53: {
            SpawnY = input.ReadFloat();
            break;
          }
          case 61: {
            SpawnZ = input.ReadFloat();
            break;
          }
          case 64: {
            WithID = input.ReadUInt64();
            break;
          }
          case 72: {
            RequestorAutoPossess = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Request = input.ReadBool();
            break;
          }
          case 16: {
            Sender = input.ReadUInt64();
            break;
          }
          case 24: {
            Authority = input.ReadUInt64();
            break;
          }
          case 34: {
            ObjName = input.ReadString();
            break;
          }
          case 45: {
            SpawnX = input.ReadFloat();
            break;
          }
          case 53: {
            SpawnY = input.ReadFloat();
            break;
          }
          case 61: {
            SpawnZ = input.ReadFloat();
            break;
          }
          case 64: {
            WithID = input.ReadUInt64();
            break;
          }
          case 72: {
            RequestorAutoPossess = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.SerializableAttribute]
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SimpleGameObjectSync : pb::IMessage<SimpleGameObjectSync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SimpleGameObjectSync> _parser = new pb::MessageParser<SimpleGameObjectSync>(() => new SimpleGameObjectSync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SimpleGameObjectSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessages.GameMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleGameObjectSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleGameObjectSync(SimpleGameObjectSync other) : this() {
      request_ = other.request_;
      sender_ = other.sender_;
      authority_ = other.authority_;
      target_ = other.target_;
      posX_ = other.posX_;
      posY_ = other.posY_;
      posZ_ = other.posZ_;
      rotX_ = other.rotX_;
      rotY_ = other.rotY_;
      rotZ_ = other.rotZ_;
      velX_ = other.velX_;
      velY_ = other.velY_;
      velZ_ = other.velZ_;
      torqueX_ = other.torqueX_;
      torqueY_ = other.torqueY_;
      torqueZ_ = other.torqueZ_;
      fData_ = other.fData_.Clone();
      ulData_ = other.ulData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleGameObjectSync Clone() {
      return new SimpleGameObjectSync(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private bool request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 2;
    private ulong sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "authority" field.</summary>
    public const int AuthorityFieldNumber = 3;
    private ulong authority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Authority {
      get { return authority_; }
      set {
        authority_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 4;
    private ulong target_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    /// <summary>Field number for the "posX" field.</summary>
    public const int PosXFieldNumber = 5;
    private float posX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosX {
      get { return posX_; }
      set {
        posX_ = value;
      }
    }

    /// <summary>Field number for the "posY" field.</summary>
    public const int PosYFieldNumber = 6;
    private float posY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosY {
      get { return posY_; }
      set {
        posY_ = value;
      }
    }

    /// <summary>Field number for the "posZ" field.</summary>
    public const int PosZFieldNumber = 7;
    private float posZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosZ {
      get { return posZ_; }
      set {
        posZ_ = value;
      }
    }

    /// <summary>Field number for the "rotX" field.</summary>
    public const int RotXFieldNumber = 8;
    private float rotX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotX {
      get { return rotX_; }
      set {
        rotX_ = value;
      }
    }

    /// <summary>Field number for the "rotY" field.</summary>
    public const int RotYFieldNumber = 9;
    private float rotY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotY {
      get { return rotY_; }
      set {
        rotY_ = value;
      }
    }

    /// <summary>Field number for the "rotZ" field.</summary>
    public const int RotZFieldNumber = 10;
    private float rotZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotZ {
      get { return rotZ_; }
      set {
        rotZ_ = value;
      }
    }

    /// <summary>Field number for the "velX" field.</summary>
    public const int VelXFieldNumber = 11;
    private float velX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VelX {
      get { return velX_; }
      set {
        velX_ = value;
      }
    }

    /// <summary>Field number for the "velY" field.</summary>
    public const int VelYFieldNumber = 12;
    private float velY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VelY {
      get { return velY_; }
      set {
        velY_ = value;
      }
    }

    /// <summary>Field number for the "velZ" field.</summary>
    public const int VelZFieldNumber = 13;
    private float velZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float VelZ {
      get { return velZ_; }
      set {
        velZ_ = value;
      }
    }

    /// <summary>Field number for the "torqueX" field.</summary>
    public const int TorqueXFieldNumber = 14;
    private float torqueX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TorqueX {
      get { return torqueX_; }
      set {
        torqueX_ = value;
      }
    }

    /// <summary>Field number for the "torqueY" field.</summary>
    public const int TorqueYFieldNumber = 15;
    private float torqueY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TorqueY {
      get { return torqueY_; }
      set {
        torqueY_ = value;
      }
    }

    /// <summary>Field number for the "torqueZ" field.</summary>
    public const int TorqueZFieldNumber = 16;
    private float torqueZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TorqueZ {
      get { return torqueZ_; }
      set {
        torqueZ_ = value;
      }
    }

    /// <summary>Field number for the "fData" field.</summary>
    public const int FDataFieldNumber = 17;
    private static readonly pbc::MapField<string, float>.Codec _map_fData_codec
        = new pbc::MapField<string, float>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForFloat(21, 0F), 138);
    private readonly pbc::MapField<string, float> fData_ = new pbc::MapField<string, float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, float> FData {
      get { return fData_; }
    }

    /// <summary>Field number for the "ulData" field.</summary>
    public const int UlDataFieldNumber = 18;
    private static readonly pbc::MapField<string, ulong>.Codec _map_ulData_codec
        = new pbc::MapField<string, ulong>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForUInt64(16, 0UL), 146);
    private readonly pbc::MapField<string, ulong> ulData_ = new pbc::MapField<string, ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, ulong> UlData {
      get { return ulData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SimpleGameObjectSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SimpleGameObjectSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Request != other.Request) return false;
      if (Sender != other.Sender) return false;
      if (Authority != other.Authority) return false;
      if (Target != other.Target) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosX, other.PosX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosY, other.PosY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosZ, other.PosZ)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotX, other.RotX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotY, other.RotY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotZ, other.RotZ)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelX, other.VelX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelY, other.VelY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelZ, other.VelZ)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TorqueX, other.TorqueX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TorqueY, other.TorqueY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TorqueZ, other.TorqueZ)) return false;
      if (!FData.Equals(other.FData)) return false;
      if (!UlData.Equals(other.UlData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Request != false) hash ^= Request.GetHashCode();
      if (Sender != 0UL) hash ^= Sender.GetHashCode();
      if (Authority != 0UL) hash ^= Authority.GetHashCode();
      if (Target != 0UL) hash ^= Target.GetHashCode();
      if (PosX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosX);
      if (PosY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosY);
      if (PosZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosZ);
      if (RotX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotX);
      if (RotY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotY);
      if (RotZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotZ);
      if (VelX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelX);
      if (VelY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelY);
      if (VelZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelZ);
      if (TorqueX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TorqueX);
      if (TorqueY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TorqueY);
      if (TorqueZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TorqueZ);
      hash ^= FData.GetHashCode();
      hash ^= UlData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Request != false) {
        output.WriteRawTag(8);
        output.WriteBool(Request);
      }
      if (Sender != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Sender);
      }
      if (Authority != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Authority);
      }
      if (Target != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Target);
      }
      if (PosX != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(PosY);
      }
      if (PosZ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(PosZ);
      }
      if (RotX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(RotX);
      }
      if (RotY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(RotY);
      }
      if (RotZ != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(RotZ);
      }
      if (VelX != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(VelX);
      }
      if (VelY != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(VelY);
      }
      if (VelZ != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(VelZ);
      }
      if (TorqueX != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(TorqueX);
      }
      if (TorqueY != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(TorqueY);
      }
      if (TorqueZ != 0F) {
        output.WriteRawTag(133, 1);
        output.WriteFloat(TorqueZ);
      }
      fData_.WriteTo(output, _map_fData_codec);
      ulData_.WriteTo(output, _map_ulData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Request != false) {
        output.WriteRawTag(8);
        output.WriteBool(Request);
      }
      if (Sender != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Sender);
      }
      if (Authority != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Authority);
      }
      if (Target != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(Target);
      }
      if (PosX != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(PosY);
      }
      if (PosZ != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(PosZ);
      }
      if (RotX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(RotX);
      }
      if (RotY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(RotY);
      }
      if (RotZ != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(RotZ);
      }
      if (VelX != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(VelX);
      }
      if (VelY != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(VelY);
      }
      if (VelZ != 0F) {
        output.WriteRawTag(109);
        output.WriteFloat(VelZ);
      }
      if (TorqueX != 0F) {
        output.WriteRawTag(117);
        output.WriteFloat(TorqueX);
      }
      if (TorqueY != 0F) {
        output.WriteRawTag(125);
        output.WriteFloat(TorqueY);
      }
      if (TorqueZ != 0F) {
        output.WriteRawTag(133, 1);
        output.WriteFloat(TorqueZ);
      }
      fData_.WriteTo(ref output, _map_fData_codec);
      ulData_.WriteTo(ref output, _map_ulData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Request != false) {
        size += 1 + 1;
      }
      if (Sender != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Sender);
      }
      if (Authority != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Authority);
      }
      if (Target != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Target);
      }
      if (PosX != 0F) {
        size += 1 + 4;
      }
      if (PosY != 0F) {
        size += 1 + 4;
      }
      if (PosZ != 0F) {
        size += 1 + 4;
      }
      if (RotX != 0F) {
        size += 1 + 4;
      }
      if (RotY != 0F) {
        size += 1 + 4;
      }
      if (RotZ != 0F) {
        size += 1 + 4;
      }
      if (VelX != 0F) {
        size += 1 + 4;
      }
      if (VelY != 0F) {
        size += 1 + 4;
      }
      if (VelZ != 0F) {
        size += 1 + 4;
      }
      if (TorqueX != 0F) {
        size += 1 + 4;
      }
      if (TorqueY != 0F) {
        size += 1 + 4;
      }
      if (TorqueZ != 0F) {
        size += 2 + 4;
      }
      size += fData_.CalculateSize(_map_fData_codec);
      size += ulData_.CalculateSize(_map_ulData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SimpleGameObjectSync other) {
      if (other == null) {
        return;
      }
      if (other.Request != false) {
        Request = other.Request;
      }
      if (other.Sender != 0UL) {
        Sender = other.Sender;
      }
      if (other.Authority != 0UL) {
        Authority = other.Authority;
      }
      if (other.Target != 0UL) {
        Target = other.Target;
      }
      if (other.PosX != 0F) {
        PosX = other.PosX;
      }
      if (other.PosY != 0F) {
        PosY = other.PosY;
      }
      if (other.PosZ != 0F) {
        PosZ = other.PosZ;
      }
      if (other.RotX != 0F) {
        RotX = other.RotX;
      }
      if (other.RotY != 0F) {
        RotY = other.RotY;
      }
      if (other.RotZ != 0F) {
        RotZ = other.RotZ;
      }
      if (other.VelX != 0F) {
        VelX = other.VelX;
      }
      if (other.VelY != 0F) {
        VelY = other.VelY;
      }
      if (other.VelZ != 0F) {
        VelZ = other.VelZ;
      }
      if (other.TorqueX != 0F) {
        TorqueX = other.TorqueX;
      }
      if (other.TorqueY != 0F) {
        TorqueY = other.TorqueY;
      }
      if (other.TorqueZ != 0F) {
        TorqueZ = other.TorqueZ;
      }
      fData_.MergeFrom(other.fData_);
      ulData_.MergeFrom(other.ulData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Request = input.ReadBool();
            break;
          }
          case 16: {
            Sender = input.ReadUInt64();
            break;
          }
          case 24: {
            Authority = input.ReadUInt64();
            break;
          }
          case 32: {
            Target = input.ReadUInt64();
            break;
          }
          case 45: {
            PosX = input.ReadFloat();
            break;
          }
          case 53: {
            PosY = input.ReadFloat();
            break;
          }
          case 61: {
            PosZ = input.ReadFloat();
            break;
          }
          case 69: {
            RotX = input.ReadFloat();
            break;
          }
          case 77: {
            RotY = input.ReadFloat();
            break;
          }
          case 85: {
            RotZ = input.ReadFloat();
            break;
          }
          case 93: {
            VelX = input.ReadFloat();
            break;
          }
          case 101: {
            VelY = input.ReadFloat();
            break;
          }
          case 109: {
            VelZ = input.ReadFloat();
            break;
          }
          case 117: {
            TorqueX = input.ReadFloat();
            break;
          }
          case 125: {
            TorqueY = input.ReadFloat();
            break;
          }
          case 133: {
            TorqueZ = input.ReadFloat();
            break;
          }
          case 138: {
            fData_.AddEntriesFrom(input, _map_fData_codec);
            break;
          }
          case 146: {
            ulData_.AddEntriesFrom(input, _map_ulData_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Request = input.ReadBool();
            break;
          }
          case 16: {
            Sender = input.ReadUInt64();
            break;
          }
          case 24: {
            Authority = input.ReadUInt64();
            break;
          }
          case 32: {
            Target = input.ReadUInt64();
            break;
          }
          case 45: {
            PosX = input.ReadFloat();
            break;
          }
          case 53: {
            PosY = input.ReadFloat();
            break;
          }
          case 61: {
            PosZ = input.ReadFloat();
            break;
          }
          case 69: {
            RotX = input.ReadFloat();
            break;
          }
          case 77: {
            RotY = input.ReadFloat();
            break;
          }
          case 85: {
            RotZ = input.ReadFloat();
            break;
          }
          case 93: {
            VelX = input.ReadFloat();
            break;
          }
          case 101: {
            VelY = input.ReadFloat();
            break;
          }
          case 109: {
            VelZ = input.ReadFloat();
            break;
          }
          case 117: {
            TorqueX = input.ReadFloat();
            break;
          }
          case 125: {
            TorqueY = input.ReadFloat();
            break;
          }
          case 133: {
            TorqueZ = input.ReadFloat();
            break;
          }
          case 138: {
            fData_.AddEntriesFrom(ref input, _map_fData_codec);
            break;
          }
          case 146: {
            ulData_.AddEntriesFrom(ref input, _map_ulData_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.SerializableAttribute]
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerControllerMessage : pb::IMessage<PlayerControllerMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerControllerMessage> _parser = new pb::MessageParser<PlayerControllerMessage>(() => new PlayerControllerMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerControllerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessages.GameMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerControllerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerControllerMessage(PlayerControllerMessage other) : this() {
      request_ = other.request_;
      sender_ = other.sender_;
      authority_ = other.authority_;
      type_ = other.type_;
      target_ = other.target_;
      other_ = other.other_;
      inputs_ = other.inputs_.Clone();
      movementVectorX_ = other.movementVectorX_;
      movementVectorY_ = other.movementVectorY_;
      rotateVectorAccumulatorX_ = other.rotateVectorAccumulatorX_;
      rotateVectorAccumulatorY_ = other.rotateVectorAccumulatorY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerControllerMessage Clone() {
      return new PlayerControllerMessage(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private bool request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "sender" field.</summary>
    public const int SenderFieldNumber = 2;
    private ulong sender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Sender {
      get { return sender_; }
      set {
        sender_ = value;
      }
    }

    /// <summary>Field number for the "authority" field.</summary>
    public const int AuthorityFieldNumber = 3;
    private ulong authority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Authority {
      get { return authority_; }
      set {
        authority_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::GameMessages.PlayerControllerMessageType type_ = global::GameMessages.PlayerControllerMessageType.PcError;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameMessages.PlayerControllerMessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 5;
    private ulong target_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    /// <summary>Field number for the "other" field.</summary>
    public const int OtherFieldNumber = 6;
    private ulong other_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Other {
      get { return other_; }
      set {
        other_ = value;
      }
    }

    /// <summary>Field number for the "inputs" field.</summary>
    public const int InputsFieldNumber = 7;
    private static readonly pbc::MapField<string, global::GameMessages.ActionInput>.Codec _map_inputs_codec
        = new pbc::MapField<string, global::GameMessages.ActionInput>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::GameMessages.ActionInput.Parser), 58);
    private readonly pbc::MapField<string, global::GameMessages.ActionInput> inputs_ = new pbc::MapField<string, global::GameMessages.ActionInput>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::GameMessages.ActionInput> Inputs {
      get { return inputs_; }
    }

    /// <summary>Field number for the "MovementVectorX" field.</summary>
    public const int MovementVectorXFieldNumber = 8;
    private float movementVectorX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MovementVectorX {
      get { return movementVectorX_; }
      set {
        movementVectorX_ = value;
      }
    }

    /// <summary>Field number for the "MovementVectorY" field.</summary>
    public const int MovementVectorYFieldNumber = 9;
    private float movementVectorY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MovementVectorY {
      get { return movementVectorY_; }
      set {
        movementVectorY_ = value;
      }
    }

    /// <summary>Field number for the "RotateVectorAccumulatorX" field.</summary>
    public const int RotateVectorAccumulatorXFieldNumber = 10;
    private float rotateVectorAccumulatorX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotateVectorAccumulatorX {
      get { return rotateVectorAccumulatorX_; }
      set {
        rotateVectorAccumulatorX_ = value;
      }
    }

    /// <summary>Field number for the "RotateVectorAccumulatorY" field.</summary>
    public const int RotateVectorAccumulatorYFieldNumber = 11;
    private float rotateVectorAccumulatorY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float RotateVectorAccumulatorY {
      get { return rotateVectorAccumulatorY_; }
      set {
        rotateVectorAccumulatorY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerControllerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerControllerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Request != other.Request) return false;
      if (Sender != other.Sender) return false;
      if (Authority != other.Authority) return false;
      if (Type != other.Type) return false;
      if (Target != other.Target) return false;
      if (Other != other.Other) return false;
      if (!Inputs.Equals(other.Inputs)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MovementVectorX, other.MovementVectorX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MovementVectorY, other.MovementVectorY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotateVectorAccumulatorX, other.RotateVectorAccumulatorX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(RotateVectorAccumulatorY, other.RotateVectorAccumulatorY)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Request != false) hash ^= Request.GetHashCode();
      if (Sender != 0UL) hash ^= Sender.GetHashCode();
      if (Authority != 0UL) hash ^= Authority.GetHashCode();
      if (Type != global::GameMessages.PlayerControllerMessageType.PcError) hash ^= Type.GetHashCode();
      if (Target != 0UL) hash ^= Target.GetHashCode();
      if (Other != 0UL) hash ^= Other.GetHashCode();
      hash ^= Inputs.GetHashCode();
      if (MovementVectorX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MovementVectorX);
      if (MovementVectorY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MovementVectorY);
      if (RotateVectorAccumulatorX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotateVectorAccumulatorX);
      if (RotateVectorAccumulatorY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(RotateVectorAccumulatorY);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Request != false) {
        output.WriteRawTag(8);
        output.WriteBool(Request);
      }
      if (Sender != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Sender);
      }
      if (Authority != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Authority);
      }
      if (Type != global::GameMessages.PlayerControllerMessageType.PcError) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (Target != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Target);
      }
      if (Other != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(Other);
      }
      inputs_.WriteTo(output, _map_inputs_codec);
      if (MovementVectorX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(MovementVectorX);
      }
      if (MovementVectorY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(MovementVectorY);
      }
      if (RotateVectorAccumulatorX != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(RotateVectorAccumulatorX);
      }
      if (RotateVectorAccumulatorY != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(RotateVectorAccumulatorY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Request != false) {
        output.WriteRawTag(8);
        output.WriteBool(Request);
      }
      if (Sender != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Sender);
      }
      if (Authority != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Authority);
      }
      if (Type != global::GameMessages.PlayerControllerMessageType.PcError) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (Target != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Target);
      }
      if (Other != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(Other);
      }
      inputs_.WriteTo(ref output, _map_inputs_codec);
      if (MovementVectorX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(MovementVectorX);
      }
      if (MovementVectorY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(MovementVectorY);
      }
      if (RotateVectorAccumulatorX != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(RotateVectorAccumulatorX);
      }
      if (RotateVectorAccumulatorY != 0F) {
        output.WriteRawTag(93);
        output.WriteFloat(RotateVectorAccumulatorY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Request != false) {
        size += 1 + 1;
      }
      if (Sender != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Sender);
      }
      if (Authority != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Authority);
      }
      if (Type != global::GameMessages.PlayerControllerMessageType.PcError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Target != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Target);
      }
      if (Other != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Other);
      }
      size += inputs_.CalculateSize(_map_inputs_codec);
      if (MovementVectorX != 0F) {
        size += 1 + 4;
      }
      if (MovementVectorY != 0F) {
        size += 1 + 4;
      }
      if (RotateVectorAccumulatorX != 0F) {
        size += 1 + 4;
      }
      if (RotateVectorAccumulatorY != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerControllerMessage other) {
      if (other == null) {
        return;
      }
      if (other.Request != false) {
        Request = other.Request;
      }
      if (other.Sender != 0UL) {
        Sender = other.Sender;
      }
      if (other.Authority != 0UL) {
        Authority = other.Authority;
      }
      if (other.Type != global::GameMessages.PlayerControllerMessageType.PcError) {
        Type = other.Type;
      }
      if (other.Target != 0UL) {
        Target = other.Target;
      }
      if (other.Other != 0UL) {
        Other = other.Other;
      }
      inputs_.MergeFrom(other.inputs_);
      if (other.MovementVectorX != 0F) {
        MovementVectorX = other.MovementVectorX;
      }
      if (other.MovementVectorY != 0F) {
        MovementVectorY = other.MovementVectorY;
      }
      if (other.RotateVectorAccumulatorX != 0F) {
        RotateVectorAccumulatorX = other.RotateVectorAccumulatorX;
      }
      if (other.RotateVectorAccumulatorY != 0F) {
        RotateVectorAccumulatorY = other.RotateVectorAccumulatorY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Request = input.ReadBool();
            break;
          }
          case 16: {
            Sender = input.ReadUInt64();
            break;
          }
          case 24: {
            Authority = input.ReadUInt64();
            break;
          }
          case 32: {
            Type = (global::GameMessages.PlayerControllerMessageType) input.ReadEnum();
            break;
          }
          case 40: {
            Target = input.ReadUInt64();
            break;
          }
          case 48: {
            Other = input.ReadUInt64();
            break;
          }
          case 58: {
            inputs_.AddEntriesFrom(input, _map_inputs_codec);
            break;
          }
          case 69: {
            MovementVectorX = input.ReadFloat();
            break;
          }
          case 77: {
            MovementVectorY = input.ReadFloat();
            break;
          }
          case 85: {
            RotateVectorAccumulatorX = input.ReadFloat();
            break;
          }
          case 93: {
            RotateVectorAccumulatorY = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Request = input.ReadBool();
            break;
          }
          case 16: {
            Sender = input.ReadUInt64();
            break;
          }
          case 24: {
            Authority = input.ReadUInt64();
            break;
          }
          case 32: {
            Type = (global::GameMessages.PlayerControllerMessageType) input.ReadEnum();
            break;
          }
          case 40: {
            Target = input.ReadUInt64();
            break;
          }
          case 48: {
            Other = input.ReadUInt64();
            break;
          }
          case 58: {
            inputs_.AddEntriesFrom(ref input, _map_inputs_codec);
            break;
          }
          case 69: {
            MovementVectorX = input.ReadFloat();
            break;
          }
          case 77: {
            MovementVectorY = input.ReadFloat();
            break;
          }
          case 85: {
            RotateVectorAccumulatorX = input.ReadFloat();
            break;
          }
          case 93: {
            RotateVectorAccumulatorY = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.SerializableAttribute]
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActionInput : pb::IMessage<ActionInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActionInput> _parser = new pb::MessageParser<ActionInput>(() => new ActionInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActionInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameMessages.GameMessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionInput(ActionInput other) : this() {
      actionName_ = other.actionName_;
      pressed_ = other.pressed_;
      released_ = other.released_;
      justPressed_ = other.justPressed_;
      changed_ = other.changed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionInput Clone() {
      return new ActionInput(this);
    }

    /// <summary>Field number for the "actionName" field.</summary>
    public const int ActionNameFieldNumber = 1;
    private string actionName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ActionName {
      get { return actionName_; }
      set {
        actionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pressed" field.</summary>
    public const int PressedFieldNumber = 2;
    private bool pressed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Pressed {
      get { return pressed_; }
      set {
        pressed_ = value;
      }
    }

    /// <summary>Field number for the "released" field.</summary>
    public const int ReleasedFieldNumber = 3;
    private bool released_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Released {
      get { return released_; }
      set {
        released_ = value;
      }
    }

    /// <summary>Field number for the "justPressed" field.</summary>
    public const int JustPressedFieldNumber = 4;
    private bool justPressed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool JustPressed {
      get { return justPressed_; }
      set {
        justPressed_ = value;
      }
    }

    /// <summary>Field number for the "changed" field.</summary>
    public const int ChangedFieldNumber = 5;
    private bool changed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Changed {
      get { return changed_; }
      set {
        changed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActionInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActionInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionName != other.ActionName) return false;
      if (Pressed != other.Pressed) return false;
      if (Released != other.Released) return false;
      if (JustPressed != other.JustPressed) return false;
      if (Changed != other.Changed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionName.Length != 0) hash ^= ActionName.GetHashCode();
      if (Pressed != false) hash ^= Pressed.GetHashCode();
      if (Released != false) hash ^= Released.GetHashCode();
      if (JustPressed != false) hash ^= JustPressed.GetHashCode();
      if (Changed != false) hash ^= Changed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ActionName);
      }
      if (Pressed != false) {
        output.WriteRawTag(16);
        output.WriteBool(Pressed);
      }
      if (Released != false) {
        output.WriteRawTag(24);
        output.WriteBool(Released);
      }
      if (JustPressed != false) {
        output.WriteRawTag(32);
        output.WriteBool(JustPressed);
      }
      if (Changed != false) {
        output.WriteRawTag(40);
        output.WriteBool(Changed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActionName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ActionName);
      }
      if (Pressed != false) {
        output.WriteRawTag(16);
        output.WriteBool(Pressed);
      }
      if (Released != false) {
        output.WriteRawTag(24);
        output.WriteBool(Released);
      }
      if (JustPressed != false) {
        output.WriteRawTag(32);
        output.WriteBool(JustPressed);
      }
      if (Changed != false) {
        output.WriteRawTag(40);
        output.WriteBool(Changed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ActionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActionName);
      }
      if (Pressed != false) {
        size += 1 + 1;
      }
      if (Released != false) {
        size += 1 + 1;
      }
      if (JustPressed != false) {
        size += 1 + 1;
      }
      if (Changed != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActionInput other) {
      if (other == null) {
        return;
      }
      if (other.ActionName.Length != 0) {
        ActionName = other.ActionName;
      }
      if (other.Pressed != false) {
        Pressed = other.Pressed;
      }
      if (other.Released != false) {
        Released = other.Released;
      }
      if (other.JustPressed != false) {
        JustPressed = other.JustPressed;
      }
      if (other.Changed != false) {
        Changed = other.Changed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ActionName = input.ReadString();
            break;
          }
          case 16: {
            Pressed = input.ReadBool();
            break;
          }
          case 24: {
            Released = input.ReadBool();
            break;
          }
          case 32: {
            JustPressed = input.ReadBool();
            break;
          }
          case 40: {
            Changed = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ActionName = input.ReadString();
            break;
          }
          case 16: {
            Pressed = input.ReadBool();
            break;
          }
          case 24: {
            Released = input.ReadBool();
            break;
          }
          case 32: {
            JustPressed = input.ReadBool();
            break;
          }
          case 40: {
            Changed = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
